### ISSUE TITLE
What to do if /dev/modem doesn't exist?

### ISSUE THREAD

**Issue by andy5995** [ksherlock/modemu#4]
I've used `modemu` some years ago. Now I don't have a modem installed on my computer. Is there a way to work-around this error?

```
andy@oceanus:~/src/modemu$ ./modemu -c "/usr/bin/minicom -l %s"
minicom: cannot open /dev/modem: No such file or directory
Comm program exited.
```

**Comment by ksherlock** [comment]
Try:

    ./modemu -c "/usr/bin/minicom -p %s"

Also look at the mtelnet script.  I was able to use minicom over modemu last year to zmodem over telnet.

**Comment by andy5995** [comment]
That worked, thank you.

Are you the original developer of modemu?

**Comment by ksherlock** [comment]
No, it was Toru Egashira, circa 1996.  I stumbled across the code last year. It didn't seem to exist anywhere else so I put it on GitHub.

**Comment by andy5995** [comment]
Oh, good idea. I was about to do that but found your repo first.

Will you be reviewing and accepting pull requests or do you suggest I work from my own fork?

**Comment by ksherlock** [comment]
You're probably better off keeping your own fork.  I haven't needed to use modemu in a while so I'm probably a poor steward :-)

**Comment by andy5995** [comment]
Ok, then. :)

My fork is at [modemu2k](https://github.com/theimpossibleastronaut/modemu2k)
